[build]
publish = "dist"
command = "pnpm nuxt:prepare && pnpm run build"

[build.environment]
NODE_VERSION = "16"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[context.deploy-preview]
  command = "pnpm install && pnpm nuxt:prepare && pnpm run build"
  publish = "dist"

[context.branch-deploy]
  command = "pnpm install && pnpm nuxt:prepare && pnpm run build"
  publish = "dist"
